site_name: Raj Dev Docs
site_description: Public Documentation & Help Guides
site_author: Raj

site_url: https://<your-username>.github.io/raj-docs-public/

docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Public:
      - Getting Started: public/getting-started.md
      - Install Java: public/how-to-install-java.md
      - FAQs: public/faq.md
      - User Guide: public/user-guide.md
      - User Dashboard: public/user-dashboard.md
      - Screenshots: public/screenshots.md
      - Manual logs: public/manual-logs.md
      - Reports: public/reports.md

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.sections

markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

# Allow indexing (public site)
extra:
  robots: |
    User-agent: *
    Allow: /

strict: true